# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractEIC <- function(specExp, mzRange, mz) {
    .Call(`_DecoMetDIA_extractEIC`, specExp, mzRange, mz)
}

findIsotope <- function(spec, numIsotope, ppm, prop) {
    .Call(`_DecoMetDIA_findIsotope`, spec, numIsotope, ppm, prop)
}

funOptim <- function(x, M, S) {
    .Call(`_DecoMetDIA_funOptim`, x, M, S)
}

mergeEIC <- function(x, y) {
    .Call(`_DecoMetDIA_mergeEIC`, x, y)
}

searchSpectra <- function(specExp, mzRange, mz, isMaxInt) {
    .Call(`_DecoMetDIA_searchSpectra`, specExp, mzRange, mz, isMaxInt)
}

checkContinuousPtsAboveThr <- function(v, iStart, num, thr, nSkipMax) {
    .Call(`_DecoMetDIA_checkContinuousPtsAboveThr`, v, iStart, num, thr, nSkipMax)
}

getContinuousPtsAboveThrIdx <- function(v, iStart, num, thr, nSkipMax) {
    .Call(`_DecoMetDIA_getContinuousPtsAboveThrIdx`, v, iStart, num, thr, nSkipMax)
}

